name: blockcypher
version: 0.3.0
description: Minimalistic library for communicating with the Blockcypher API.
author: Harm Aarts <harm@aarts.email>
homepage: https://github.com/haarts/blockcypher_client

dependencies:
    uuid: ^2.0.4
    web_socket_channel: ^1.1.0
    http: ^0.12.0

dev_dependencies:
    test: ^1.11.1
    pedantic: ^1.9.0
    mock_web_server:
        git:
            url: git://github.com/haarts/MockWebServer
            ref: f8079e9f52ac45d920c677e545316a6905eaf819

environment:
    sdk: ">=2.1.0 <3.0.0"
